/* Generated by wayland-scanner 1.21.90 */

/* copy right reserved
 */

#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"


static const struct wl_interface *obric_launch_setting_types[] = {
	NULL,
	NULL,
	NULL,
};

static const struct wl_message obric_launch_setting_requests[] = {
	{ "try_launch_from", "uss", obric_launch_setting_types + 0 },
};

WL_EXPORT const struct wl_interface obric_launch_setting_interface = {
	"obric_launch_setting", 1,
	1, obric_launch_setting_requests,
	0, NULL,
};

